### ISSUE TITLE
AWS ECS - propagate tags to tasks

### ISSUE THREAD

**Issue by alexmaras** [tryretool/terraform-retool-modules#39]
In the AWS ECS setup, the `aws_ecs_service` resource doesn't propagate tags to the tasks. This results in large amounts of fargate VCPU usage going untagged and potentially not visible in AWS Cost Explorer. 

Could we get this added as per the [AWS terraform documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_service#propagate_tags) documentation on the service resource. There are two options, so perhaps defaulting to one and allowing a variable for the other would make sense.

**Comment by samsternatretool** [comment]
@alexmaras thanks for the feedback, we'll take a look. If you know how this should be solved and feel comfortable submitting a PR we will definitely try to get it merged!

**Comment by alexmaras** [comment]
@samsternatretool - https://github.com/tryretool/terraform-retool-modules/pull/40 

Forgot to link across to this when I put it up.

**Comment by samsternatretool** [comment]
Fixed by https://github.com/tryretool/terraform-retool-modules/pull/40

Thank you @alexmaras for contributing!
