### ISSUE TITLE
Enable Optional Multi-AZ for RDS

### ISSUE THREAD

**Issue by tkosushi** [tryretool/terraform-retool-modules#67]
To enhance the availability of RDS instance in the production environment, I would like to request the ability to optionally enable Multi-AZ deployment. 
This change will help ensure higher availability and reliability for our database services.
(I was actually going to send a pull request, but it wasn't allowed, so I made an Issue.)

### Proposed Changes:

Add the below code.
- main.tf
```
resource "aws_db_instance" "this" {
...

  multi_az                     = var.rds_multi_az
```

- variables.tf
```
variable "rds_multi_az" {
  type        = bool
  default     = false
  description = "Whether the RDS instance should have Multi-AZ enabled. Defaults to false."
}
```

### Expected Changes:

Introduce a new variable var.rds_multi_az to control the Multi-AZ setting.
Ensure the multi_az attribute in the aws_db_instance resource is set based on the new variable.

**Comment by samsternatretool** [comment]
@tkosushi this seems like a safe and reasonable change! We'd be happy to accept your PR, can you explain why you say you're not allowed? Is that a policy on your side?

**Comment by tkosushi** [comment]
@samsternatretool 
Thank you for your response.
My apologies, I encountered a permission error when pushing the branch, but it was due to my mistake. 
I have now created the pull request. https://github.com/tryretool/terraform-retool-modules/pull/68

I would like to close this issue.
